/*
 * Query #1 : 	Show the name of the hospital, its address and the number of deaths
				for each registered hospital.
 * */
SELECT h.HOSPITAL_NAME, h.HOSPITAL_DIRECTION, COUNT(v.DEATH_DATE) AS NUM_OF_DEATHS
FROM HOSPITAL h
LEFT JOIN VICTIM v ON h.HOSPITAL_ID = v.HOSPITAL_ID AND v.DEATH_DATE IS NOT NULL
GROUP BY h.HOSPITAL_ID, h.HOSPITAL_NAME, h.HOSPITAL_DIRECTION
ORDER BY NUM_OF_DEATHS DESC;


/*
 * Query #2 : 	Show the first name, last name of all quarantined victims who
				presented an effectiveness greater than 5 in the treatment
				"Blood transfusions".
 * */

SELECT v.VICTIM_NAME, v.VICTIM_LAST_NAME
FROM VICTIM v
JOIN TREATMENT_VICTIM tv ON v.VICTIM_ID = tv.VICTIM_ID
JOIN TREATMENT t ON tv.TREATMENT_ID = t.TREATMENT_ID
WHERE v.VICTIM_STATUS = 'En cuarentena'
AND t.TREATMENT_NAME = 'Transfusiones de sangre'
AND tv.VICTIM_EFECTIVITY > 5
ORDER BY v.VICTIM_NAME, v.VICTIM_LAST_NAME;

/*
 * Query #3 : 	Show the name, last_name and address of the deceased victims with
				more than three associated people.
 * */

SELECT VICTIM_NAME, VICTIM_LAST_NAME, VICTIM_DIRECTION
FROM VICTIM
INNER JOIN (
    SELECT VICTIM_ID
    FROM CONTACT
    GROUP BY VICTIM_ID
    HAVING COUNT(*) > 3
) alias ON VICTIM.VICTIM_ID = alias.VICTIM_ID
WHERE DEATH_DATE IS NOT NULL
ORDER BY VICTIM_NAME, VICTIM_LAST_NAME;


/*
 * Query #4 : 	Show the first and last name of all victims in state
				"Suspended" who had physical contact of the "Kiss" type with more than
				2 of his associates.
 * */

SELECT VICTIM_NAME, VICTIM_LAST_NAME
FROM VICTIM
INNER JOIN CONTACT
ON VICTIM.VICTIM_ID = CONTACT.VICTIM_ID
WHERE VICTIM_STATUS = 'Suspendida'
AND CONTACT.PHYSICAL_CONTACT = 'Beso'
GROUP BY VICTIM_NAME, VICTIM_LAST_NAME
HAVING COUNT(DISTINCT CONTACT.ASSOCIATED_ID) > 2;


/*
 * Query #5 : 	Top 5 victims who have applied the most treatments of the
				“Oxygen” treatment.
 * */

SELECT v.VICTIM_ID ,v.VICTIM_NAME, v.VICTIM_LAST_NAME, COUNT(tv.TREATMENT_VICTIM_ID) AS NUM_TREATMENTS
FROM VICTIM v
JOIN TREATMENT_VICTIM tv ON v.VICTIM_ID = tv.VICTIM_ID
JOIN TREATMENT t ON tv.TREATMENT_ID = t.TREATMENT_ID
WHERE t.TREATMENT_NAME = 'Oxigeno'
GROUP BY v.VICTIM_ID,v.VICTIM_NAME, v.VICTIM_LAST_NAME
ORDER BY v.VICTIM_NAME, v.VICTIM_LAST_NAME, NUM_TREATMENTS DESC
FETCH FIRST 5 ROWS ONLY;


/*
 * Query #6 : 	Show first name, last name, and date of death for all
				victims who moved through the address “1987 Delphine Well” to the
				which were applied "Management of blood pressure" as treatment
 * */

SELECT VICTIM_NAME, VICTIM_LAST_NAME, DEATH_DATE
FROM VICTIM 
JOIN TREATMENT_VICTIM ON VICTIM.VICTIM_ID = TREATMENT_VICTIM.VICTIM_ID
JOIN TREATMENT ON TREATMENT_VICTIM.TREATMENT_ID = TREATMENT.TREATMENT_ID
JOIN LOCATION ON VICTIM.VICTIM_ID = LOCATION.VICTIM_ID
WHERE LOCATION.VICTIM_LOCATION = '1987 Delphine Well' AND TREATMENT.TREATMENT_NAME = 'Manejo de la presion arterial'
ORDER BY VICTIM_NAME ASC, VICTIM_LAST_NAME ASC;
--AND (DEATH_DATE IS NOT NULL OR VICTIM.VICTIM_STATUS ='Muerte')

/*
 * Query #7 : 	Show first name, last name and address of the victims who have less
				of 2 associateds who have been in a hospital and who were
				only two treatments have been applied
 * */

SELECT V.VICTIM_NAME, V.VICTIM_LAST_NAME, V.VICTIM_DIRECTION
FROM VICTIM V
WHERE V.VICTIM_ID IN (
	SELECT TV.VICTIM_ID
	FROM TREATMENT_VICTIM TV
	GROUP BY TV.VICTIM_ID
	HAVING COUNT(DISTINCT TV.TREATMENT_ID) = 2
) AND V.VICTIM_ID NOT IN (
	SELECT DISTINCT C1.VICTIM_ID
	FROM CONTACT C1
	JOIN VICTIM V1 ON C1.ASSOCIATED_ID = V1.VICTIM_ID
	JOIN VICTIM V2 ON C1.VICTIM_ID = V2.VICTIM_ID AND V1.VICTIM_NAME = V2.VICTIM_NAME AND V1.VICTIM_LAST_NAME = V2.VICTIM_LAST_NAME
	GROUP BY C1.VICTIM_ID, C1.ASSOCIATED_ID
	HAVING COUNT(DISTINCT V2.VICTIM_ID) > 2
)ORDER BY V.VICTIM_NAME, V.VICTIM_LAST_NAME;

/*
 * Query #8 : 	Show the month number of the date of the first suspicion,
				name and surname of the victims who received the most treatments
				applied and those that less. (All in the same query).
 * */
SELECT 
TO_CHAR(FIRST_SUSPICION_DATE, 'MM') AS MONTH,
V.VICTIM_NAME,
V.VICTIM_LAST_NAME,
COUNT(TV.TREATMENT_ID) AS TREATMENT_COUNT
FROM VICTIM V
LEFT JOIN TREATMENT_VICTIM TV ON V.VICTIM_ID = TV.VICTIM_ID
GROUP BY TO_CHAR(FIRST_SUSPICION_DATE, 'MM'), V.VICTIM_NAME, V.VICTIM_LAST_NAME
HAVING COUNT(TV.TREATMENT_ID) = (SELECT MAX(TREATMENT_COUNT) FROM (
SELECT COUNT(TREATMENT_ID) AS TREATMENT_COUNT
FROM TREATMENT_VICTIM
GROUP BY VICTIM_ID
))
OR COUNT(TV.TREATMENT_ID) = (SELECT MIN(TREATMENT_COUNT) FROM (
SELECT COUNT(TREATMENT_ID) AS TREATMENT_COUNT
FROM TREATMENT_VICTIM
GROUP BY VICTIM_ID
))
ORDER BY TREATMENT_COUNT DESC,V.VICTIM_NAME ASC, V.VICTIM_LAST_NAME ASC;



/*
 * Query #9 : 	Show the percentage of victims that correspond to each
				hospital.
 * */

SELECT 
H.HOSPITAL_NAME, 
COUNT(V.VICTIM_ID) * 100 / (SELECT COUNT(*) FROM VICTIM) AS PERCENTAGE 
FROM HOSPITAL H 
LEFT JOIN VICTIM V ON H.HOSPITAL_ID = V.HOSPITAL_ID 
GROUP BY H.HOSPITAL_NAME 
ORDER BY PERCENTAGE DESC, H.HOSPITAL_NAME ASC;



/*
 * Query #10 : 	Show the percentage of the most common physical contact of each
				hospital as follows: hospital name, name of the
				physical contact, percentage of victims.
 * */


SELECT HOSPITAL_NAME, PHYSICAL_CONTACT, PORCENTAJE_VICTIMAS
FROM (
	SELECT 
	HOSPITAL.HOSPITAL_NAME, 
	CONTACT.PHYSICAL_CONTACT, 
	COUNT(*) * 100.0 / (
		SELECT DISTINCT COUNT(*) 
		FROM CONTACT 
		INNER JOIN VICTIM ON VICTIM.VICTIM_ID = CONTACT.VICTIM_ID 
		WHERE VICTIM.HOSPITAL_ID = VICTIM1.HOSPITAL_ID 
	) AS PORCENTAJE_VICTIMAS,
	ROW_NUMBER() OVER (PARTITION BY HOSPITAL.HOSPITAL_NAME ORDER BY COUNT(*) DESC) AS RN
	FROM 
	VICTIM VICTIM1 
	INNER JOIN CONTACT ON CONTACT.VICTIM_ID = VICTIM1.VICTIM_ID 
	INNER JOIN HOSPITAL ON HOSPITAL.HOSPITAL_ID = VICTIM1.HOSPITAL_ID 
	GROUP BY 
	HOSPITAL.HOSPITAL_NAME, 
	CONTACT.PHYSICAL_CONTACT, 
	VICTIM1.HOSPITAL_ID
) 
WHERE RN = 1
ORDER BY PORCENTAJE_VICTIMAS DESC;